server:
  port: 8081  # Set the port for the service
  
spring:
  application:
    name: employee-department-service  # Service name
  datasource:
    url: jdbc:mysql://localhost:3306/your_db_name  # MySQL database URL
    username: root  # Database username
    password: virat  # Database password
  jpa:
    hibernate:
      ddl-auto: update  # Hibernate settings
    show-sql: true  # Show SQL queries

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka server URL
